### ISSUE TITLE
你好，可以增加是否对信息进行Json格式化显示么

### ISSUE THREAD

**Issue by violetnight** [jenly1314/LogX#2]

**Comment by jenly1314** [comment]
在尽量保证代码干净的情况下，如有必要，抽空可以考虑加个工具类或扩展函数来支持json格式化。

**Comment by jenly1314** [comment]
已支持格式化json，详情请查看当前最新发布的版本（v1.1.0）。

**Comment by violetnight** [comment]
> 已支持格式化json，详情请查看当前最新发布的版本（v1.1.0）。

好滴好滴，谢谢
